### ISSUE TITLE
Research API

### ISSUE THREAD

**Issue by haizhou85** [HTTP-Warriors/Stock-Portfolio-Backend#1]
Intrinio API
https://account.intrinio.com/account/overview
use team email to login, password is the same one.
team email is sdhttpwarriors@gmail.com

**Comment by richandcreamy** [comment]
https://twelvedata.com/docs#getting-started I think this is the best one for us to use since it'll provide realtime data and 500 requests per minute. The key is in our project gmail account.

I'll close this out and move to done. Feel free to reopen if need be.
